### ISSUE TITLE
New York server is not working

### ISSUE THREAD

**Issue by fu-sen** [domcloud/domcloud-id#3]
The New York server `*.domcloud.io` has not been working for a few days.

The status page is displayed as if the server itself is normal.
https://status.domcloud.id/

But it's not really working. I can't browse the web I built at all, and Deploy after New Host always has this log:
```
CRITICAL: SSH login failed. Most procedure will not execute.
```

**Comment by willnode** [comment]
Sorry. It's SSH misconfiguration. I have fixed it recently.

**Comment by fu-sen** [comment]
I'm sorry, too. This was supposed to be an issue to [domcloud-io](https://github.com/domcloud/domcloud-io).

**Comment by fu-sen** [comment]
At the same time, the response of Portal is getting worse. Is it related to the New York server?

**Comment by willnode** [comment]
No. It's because I have separate it due to domcloud/domcloud-io#7. I was forgot to disable some unneeded services there, so it should be fast right now.

**Comment by fu-sen** [comment]
I checked immediately, but the New York server is still having problems.

**Comment by willnode** [comment]
Found the culprit is on SSL certificates.

I believe it has been fixed now.

**Comment by fu-sen** [comment]
Oh, I was aware of it, so maybe I should have commented on it for you to notice. 😣

I created a New Host on nyc and was able to confirm a successful build. Thank you! 👍
I can close this issue.
